Add layout specific injections
yiisoft/yii-view pull request #102
Opened 2024-04-09 18:30 UTC by vjik

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | Fix #101

2024-05-06 18:23 UTC, samdark requested changes

2024-05-06 18:23 UTC, samdark commented on src/ViewRenderer.php
> +            $parameters = array_merge($parameters, $injection->getCommonParameters());
`array_merge` within `foreach()` isn't great.

See https://www.exakat.io/en/speeding-up-array_merge/

2024-05-06 18:23 UTC, samdark commented on src/ViewRenderer.php
> +            $parameters = array_merge($parameters, $injection->getLayoutParameters());
Same here.

2024-05-06 18:23 UTC, samdark commented on src/ViewRenderer.php
> +            $tags = array_merge($tags, $injection->getMetaTags());
Same here.

2024-05-06 18:23 UTC, samdark commented on src/ViewRenderer.php
> +            $tags = array_merge($tags, $injection->getLinkTags());
Same here.

2024-05-07 08:37 UTC, vjik commented on src/ViewRenderer.php
> +            $parameters = array_merge($parameters, $injection->getCommonParameters());
Done

2024-05-09 10:04 UTC, samdark approved these changes

2024-05-14 07:39 UTC, merged